language: node_js

node_js:
  - "4"

install:
  - npm install

script:
  - npm run build
  - npm test

#after_success:
#    - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
