language: node_js

node_js:
  - "8"
  - "stable"

install:
  - npm install
  - npm install vue

script:
  - npm run build
  - npm test

after_success:
  - npm run coveralls
  - npm run codecov

notifications:
  email: false
